# Generated by Django 2.2.7 on 2019-11-28 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento ')),
                ('parentesco', models.PositiveSmallIntegerField(choices=[(1, 'Padre'), (2, 'Madre'), (3, 'Hijo'), (4, 'Hija')], default=1, verbose_name='Parentesco')),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_informe', models.DateField(verbose_name='Fecha de informe ')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento ')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
            },
        ),
        migrations.CreateModel(
            name='ParteInforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Sanitaria'), (2, 'Funcional'), (3, 'Psiquica'), (4, 'Social'), (5, 'Terapia ocupacional')], default=1, verbose_name='Tipo')),
                ('valoracion_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valoración')),
                ('objetivos', models.CharField(max_length=150, verbose_name='Objetivos')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Informes', to='PROGRAMAINDIVIDUALIZADO.Informe')),
            ],
            options={
                'verbose_name': 'Parte Informe',
                'verbose_name_plural': 'Partes Informes',
            },
        ),
    ]
