# Generated by Django 2.2.7 on 2019-11-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROGRAMAINDIVIDUALIZADO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parteinforme',
            name='objetivos',
            field=models.CharField(blank=True, max_length=150, verbose_name='Objetivos'),
        ),
        migrations.AlterField(
            model_name='parteinforme',
            name='valoracion_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Valoración'),
        ),
    ]
