# Generated by Django 2.2.7 on 2019-11-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROGRAMAINDIVIDUALIZADO', '0002_auto_20191128_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parteinforme',
            name='objetivos',
            field=models.TextField(blank=True, max_length=4000, verbose_name='Objetivos'),
        ),
        migrations.AlterField(
            model_name='parteinforme',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[('Sanitaria', 'Sanitaria'), ('Funcional', 'Funcional'), ('Psiquica', 'Psiquica'), ('Social', 'Social'), ('Terapia ocupacional', 'Terapia ocupacional')], default='Sanitaria', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='parteinforme',
            name='valoracion_inicial',
            field=models.TextField(max_length=350, verbose_name='Valoración'),
        ),
    ]
