# Generated by Django 2.2.7 on 2019-11-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROGRAMAINDIVIDUALIZADO', '0003_auto_20191128_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='parteinforme',
            name='objetivos',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Objetivos'),
        ),
        migrations.AlterField(
            model_name='parteinforme',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sanitaria'), (2, 'Funcional'), (3, 'Psiquica'), (4, 'Social'), (5, 'Terapia ocupacional')], default=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='parteinforme',
            name='valoracion_inicial',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='Valoración'),
        ),
    ]
