# Generated by Django 2.2.7 on 2019-11-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROGRAMAINDIVIDUALIZADO', '0005_auto_20191128_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='nombre',
            field=models.CharField(default='Informe', max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
