# Generated by Django 2.2.7 on 2019-11-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ManyToManyField(related_name='Categorias', to='catalog.Categoria'),
        ),
    ]
