# Generated by Django 2.2.7 on 2019-11-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191128_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ManyToManyField(blank=True, related_name='Categorias', to='catalog.Categoria'),
        ),
    ]
