# Generated by Django 2.2.7 on 2019-11-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191128_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=4000, verbose_name='Descripcion'),
        ),
    ]
