# Generated by Django 2.2.7 on 2019-11-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191128_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='url_imagen',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Imagen'),
        ),
    ]
