# Generated by Django 2.2.7 on 2019-11-28 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('siglas', models.CharField(max_length=50, verbose_name='Siglas')),
            ],
            options={
                'verbose_name': 'Aeropuerto',
                'verbose_name_plural': 'Aeropuertos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('fecha_salida', models.DateField(verbose_name='Fecha Salida')),
                ('fecha_llegada', models.DateField(verbose_name='Fecha Llegada')),
                ('codigo_vuelo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Vuelo')),
                ('aeropuerto_llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aeropuerto_Salida', to='vuelos.Aeropuerto', verbose_name='Aeropuerto Llegada')),
                ('aeropuerto_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aeropuerto_Llegada', to='vuelos.Aeropuerto', verbose_name='Aeropuerto Salida')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha Reserva')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='vuelos.Cliente')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vuelo', to='vuelos.Vuelo')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['cliente', 'fecha_reserva'],
            },
        ),
    ]
