# Generated by Django 2.2.7 on 2019-11-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_auto_20191129_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Cliente'},
        ),
    ]
